basic_suite_test.go

Currently, golangci job is red on master branch https://github.com/networkservicemesh/integration-k8s-kind/runs/935848369. This PR fixes the problem.

Fix golangci error for master branch

---

.github/workflows/ci.yaml

Automerge job cannot merge PRs from the nsmbot

fix: automerge job working incorrectly

---

entry_point_test.go

Previously we've moved features to separate suite from basic suite https://github.com/networkservicemesh/deployments-k8s/pull/506
Now we need to enable this suite on ci.

Add features suite to run on ci

---

entry_point_test.go

Temporary skips heal tests to test veth pair. Should be unskipped after https://github.com/networkservicemesh/deployments-k8s/pull/1789 merged.

[qfix] Temporary skip heal tests

---

.github/workflows/ci.yaml

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
Since version 1.19 k8s get a few new features such as startupProbe, projected volumes (that are using in https://github.com/networkservicemesh/deployments-k8s/pull/2898)
That also can be used in our examples to make them simpler. 
So this PR just disables 1.17 and 1.18 where these features are not supported and adds testing on 1.22.

feat: Drop k8s versions 1.17 and 1.18 and add 1.22 on ci

---

.github/workflows/ci.yaml
main_test.go

Added remote vlan examples entry point
Related PR: deployments-k8s/#4465
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>

Add more remote vlan examples (deployments-k8s#4433)

---

go.mod
go.sum
tests_interdomain/interdomain_test.go

We recently renamed `floating_interdomain` suite into `multicluster`. We need to change related references in tests.
https://github.com/networkservicemesh/integration-k8s-kind/pull/745#event-7821876888

Manual update of dependencies

---

.github/workflows/ci.yaml
README.md
calico/kustomization.yaml
calico/patch.yaml

Update calico version

---

.github/workflows/ci.yaml

Closes: https://github.com/networkservicemesh/integration-k8s-kind/issues/773
To be sure that `installations` CRD is ready

Fix kubectl wait for calico

---

.github/workflows/ci.yaml
tests_afxdp/afxdp_test.go

This PR adds tests that use AF_XDP management interface
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/283

Add af_xdp tests

---

tests_single/feature_test.go

https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/5521878392
`TestSelect_forwarder` adds new forwarders that accidentally can be used by other tests

Run TestSelect_forwarder sequentially

---

.github/workflows/update-dependent-repositories-gomod.yaml

Remove `automerge completed` trigger from `update-dependent-repositories-gomod` workflow so it doesn't run two times

[qfix] Remove `automerge completed` trigger from `update-dependent-repositories-gomod` workflow

---

.github/workflows/ci.yaml
tests_ovs_extended/feature_ovs_test.go
tests_ovs_extended/heal_ovs_test.go
tests_single/ovs_test.go

Related issue: networkservicemesh/deployments-k8s#9778

Update ovs kind tests

---

.github/workflows/ci.yaml

https://github.com/networkservicemesh/deployments-k8s/issues/11186
This is a baby step for the tanzu integration testing. We can merge it for now, and replace unmanaged cluster testing with k8s grid tanzu env when we get a working configuration on packet clusters.

Add tanzu unmanaged cluster testing

---

.github/workflows/ci.yaml

https://github.com/networkservicemesh/integration-k8s-kind/issues/988
This is a known upload-artifact v4 action issue, reported here: https://github.com/actions/upload-artifact/issues/478
Related breaking changes (source: https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes):
> 2. Uploading to the same named Artifact multiple times.
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
Though many users found the old way much more convenient and preferred to rollback to v3 until [the issue](https://github.com/actions/upload-artifact/issues/478) …

Rollback upload-artifact action to v3.

---

tests_single/feature_test.go
tests_single/ipsec_test.go

https://github.com/networkservicemesh/integration-k8s-kind/issues/1007
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/10317450720/job/28561772085?pr=1026

Exclude vl3 tests from parallel suite in features and ipsec tests

---

.github/workflows/ci.yaml

In some cases the NSM_KUBERNETES_VERION variable is not accessible. This fix makes it safe.

fix env setting in ci workflow

---

.github/workflows/ci.yaml

The artifact creation should not fail when more test failure occurs in different kind version.
Now the kind version is included into the artifact name.
Example test of upload-artifact action workflow: https://github.com/actions/upload-artifact/blob/65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08/.github/workflows/test.yml

Fix upload artifact on ci workflow

---

.github/workflows/ci.yaml

Adjusts the artifact name generation to support `matrix.image` values that may include a `@` digest, ensuring consistent behavior regardless of image format.

Fix update artifact name to handle images with digest

---

.github/workflows/ci.yaml
calico/kustomization.yaml
calico/patch.yaml

Currently calico job fails in setup phase only. 
Usually the integration test fails to pre-fetch the required images. If this step fails the job still successful.
So calico CI tests has no real meaning.

Uplift calico and vpp-dataplane in CI

---

.github/workflows/ci.yaml

https://github.com/networkservicemesh/integration-k8s-kind/issues/1079
This PR temporarily adds `continue-on-error: true` to the Integration tests  step of the `kind-ovs-extra` job in the CI workflow to prevent it from causing the entire workflow to fail due to its current faulty behavior.
**Note**: This is a stopgap measure. Once the underlying issue in the suite is resolved, this flag should be removed to restore proper CI failure detection.

Temporarily prevent kind-ovs-extra CI step from failing
