.github/workflows/ci.yaml

Add using kind cluster-config.yaml on ci

---

deployments/registry-memory.yaml

Update after the fix https://github.com/networkservicemesh/cmd-registry-memory/pull/76

Update envs for registry memory

---

.github/workflows/ci.yaml

This PR is part of https://github.com/networkservicemesh/cmd-template/issues/20

feat: Cancel testing in case of push during testing

---

.github/workflows/pr-for-updates.yaml
cluster-config.yaml

Add pr for updates

---

.github/workflows/ci.yaml

Allow to automerge job merge yaml files

---

.github/workflows/ci.yaml

fix: automerge job is skipped on update from cmd-* app

---

deployments/nsc.yaml
deployments/nse.yaml
deployments/nsmgr.yaml

The bot cannot update the version of deployments due to master images are broken for some reasons. This PR  sets stable versions.

fix: Set versions of applications manually 

---

basic_suite_test.go
cmd/fake-cross-nse/go.mod
cmd/fake-cross-nse/go.sum
deployments/nsc.yaml
deployments/nse.yaml
deployments/nsmgr.yaml
deployments/registry-memory.yaml
deployments/registry-proxy-dns.yaml

Update fake forwarder + set latest images manually

---

.github/workflows/ci.yaml

Do not checkout latest deployments-k8s

---

.github/workflows/update-dependent-repositories-gomod.yaml

feat: add packet dependent repository

---

.github/workflows/ci.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

fix: update-dependent-repositories is not working

---

.github/workflows/ci.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

fix: update deps job has using an old version of integration-tests

---

.github/workflows/ci.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Add gke to dependent repositories

---

.github/workflows/automerge.yaml
.github/workflows/ci.yaml

fix: automerge job can not do merge

---

.github/workflows/automerge.yaml

Related to https://github.com/networkservicemesh/integration-k8s-kind/pull/150

fix: automerge job can not do merge #2

---

.github/workflows/automerge.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

fix: Do not allow to NSMBot merge red PRs in integration-k8s-kind

---

.github/workflows/automerge.yaml

Fixes spam of update jobs from bot:
https://github.com/networkservicemesh/integration-k8s-kind/actions

fix: Set correct status for automerge action on 'ci' workflow failure or cancelled

---

.github/workflows/ci.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Closes https://github.com/networkservicemesh/integration-k8s-kind/issues/197

fix: "integration-k8s-kind spams upstream repos on ci workflow canceling"

---

.github/workflows/update-dependent-repositories-gomod.yaml

Update go version to 1.16

---

.github/workflows/update-dependent-repositories-gomod.yaml

Add aks to dependent repositories

---

.github/workflows/update-dependent-repositories-gomod.yaml

Add aws to dependent repositories

---

.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

Subscribe interdomain ci repository on updates

---

entry_point_test.go
go.mod
go.sum

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
related to https://github.com/networkservicemesh/deployments-k8s/issues/1693

Added heal suit test

---

go.mod
go.sum

Signed-off-by: Vladimir Popov <vladimir.popov@xored.com>

Manually update to the latest integration-tests version

---

.github/workflows/ci.yaml
entry_point_test.go
go.mod
go.sum

Signed-off-by: Vladimir Popov <vladimir.popov@xored.com>

Enable heal tests and increase timeout

---

.github/workflows/ci.yaml

Fix container logs collecting

---

.github/workflows/automerge.yaml
.github/workflows/pr-for-updates.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
part of https://github.com/networkservicemesh/cmd-template/issues/64

Updated nsmbot message

---

.github/workflows/ci.yaml
cluster-config-old.yaml
go.mod
go.sum

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
fixes issues, related to spire registrator on older kind versions

Added support for older kind versions

---

.github/workflows/ci.yaml
go.mod
go.sum

`40m` is not enough with heal tests:
https://github.com/networkservicemesh/integration-k8s-kind/runs/4186925579?check_suite_focus=true

[qfix] Increase test timeout

---

.github/workflows/ci.yaml

Signed-off-by: Ed Warnicke <hagbard@gmail.com>

Add testing for k8s v1.23.0

---

entry_point_test.go

Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

Add observability suite

---

entry_point_test.go

[qfix] Enable observability test on ci

---

.github/workflows/ci.yaml

Signed-off-by: Nikolay Chunosov <n.chunosov@yandex.ru>
Requted by issue https://github.com/networkservicemesh/deployments-k8s/issues/4467

Drop kind 1.17

---

calico_test.go

Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/325

Enable feature suite with Calico

---

calico_test.go

Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/633

Disable Calico vl3 test

---

.github/workflows/ci.yaml
calico/kustomization.yaml

Update calico to v3.23

---

.github/workflows/ci.yaml

Signed-off-by: Ed Warnicke <hagbard@gmail.com>

Add testing with k8s v1.24.0

---

.github/workflows/ci.yaml
go.mod
go.sum

Closes:  https://github.com/networkservicemesh/integration-k8s-kind/pull/672

Increase test timeout

---

.github/workflows/ci.yaml
main_test.go

Issue: https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/issues/1

Add k8s_monolith test

---

README.md

Add Calico setup to readme

---

.github/workflows/ci.yaml
interdomain_test.go

Signed-off-by: Marina Shustova <marina.shustova@xored.com>
Closes https://github.com/networkservicemesh/integration-k8s-kind/pull/699

Add floating interdomain test

---

.github/workflows/ci.yaml
go.mod
go.sum

Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>

bump: Update k8s versions

---

.github/workflows/ci.yaml
go.mod
go.sum

Signed-off-by: Vyacheslav Tumanov <me@slavatumanov.me>

Increase single cluster testing time to avoid fails on ci

---

.github/workflows/ci.yaml
tests_single/ipsec_test.go

Add ipsec tests

---

.github/workflows/update-dependent-repositories-gomod.yaml

https://github.com/networkservicemesh/integration-k8s-kind/issues/862

Add input with base repository in `update-dependent-repositories-gomod` workflow

---

.github/workflows/ci.yaml
tests_interdomain/interdomain_test.go

https://github.com/networkservicemesh/integration-tests/issues/2862

Run multicluster suite in parallel

---

tests_interdomain/interdomain_test.go

https://github.com/networkservicemesh/deployments-k8s/issues/9647

Add multicluster heal tests

---

.github/workflows/ci.yaml

https://github.com/networkservicemesh/integration-k8s-kind/issues/974

Update some github actions

---

.github/workflows/ci.yaml
.github/workflows/perfromance-testing.yaml

https://github.com/networkservicemesh/.github/issues/55

Make KUBERNETES_VERSION env consistent across all jobs

---

.github/workflows/ci.yaml
.golangci.yml
go.mod
go.sum

Issue: https://github.com/networkservicemesh/deployments-k8s/issues/12294

Update go to 1.23

---

.github/workflows/ci.yaml

Fixes https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/12417099147/attempts/3
<sub><a href="https://front.hc.engineering/guest/networkservicemesh?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZhNmYzMmMyOWE3OGFmZmY2NmVlMDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Im5ldHdvcmtzZXJ2aWNlbWVzaCJ9.CDqHfk_P2xNJHTffiqFbZ54wwn1Ay2Z0h2wZgB575uc">Huly&reg;: <b>NETWO-20876</b></a></sub>

downgrade minor version for kind@v1.30

---

.github/workflows/update-dependent-repositories-gomod.yaml

https://github.com/networkservicemesh/deployments-k8s/issues/12681

Remove unsupported integration tests from workflows

---

.github/workflows/ci.yaml

Updated upload-artifact github action to v4.

Update upload-artifact action to v4

---

.github/dependabot.yml

This PR enables Dependabot in the repository to automatically check GitHub Actions versions weekly and create pull requests for any outdated dependencies found.

Enable dependabot for updating github actions

---

.github/dependabot.yml
.github/workflows/automerge.yaml

This PR introduces a prefix for commits and pull requests created by Dependabot for uplifting github actions.

Introduce prefix for commits created by dependabot

---

.github/workflows/ci.yaml

Issue link: https://github.com/networkservicemesh/integration-k8s-kind/issues/1041

Update ci.yaml with new KIND and KUBERNETES versions
